---
- name: Add the OS specific variables
  include_vars: '{{ ansible_os_family }}.yml'
  tags: [ 'configuration', 'package', 'service', 'chrony' ]
  
- name: Install the required packages in Redhat derivatives
  yum: name=chrony state={{ chrony_pkg_state }}
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'chrony' ]
  
- name: Remove NTP if installed in Redhat
  yum: name=ntp state=absent
  when: ansible_os_family == 'RedHat'
  tags: [ 'package', 'chrony' ]

- name: Install the require packages in Debian derivatives
  apt: name=chrony state={{ chrony_pkg_state }}
  when: ansible_os_family == 'Debian'
  tags: [ 'package', 'chrony' ]

- name: Copy the chrony.conf template file
  template: src=chrony.conf.j2 dest={{ chrony_config_location }}
  notify:
  - restart chrony
  tags: [ 'configuration', 'package', 'chrony' ]

- name: Start/stop chrony service
  service: name={{ chrony_service_name }} state={{ chrony_service_state }} enabled={{ chrony_service_enabled }}
  tags: [ 'service', 'chrony' ]
